apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: apr7-newgitopsdoc-2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/apr7-newgitopsdoc-2:c424b501ed88832097eba120e5cca9ace5acce33@sha256:8a5632cfdb9f420e9100c4b35b8d46ae87be01a96a4ad7f71b2883410d942a03 # use pre-built to bootstrap
          name: app-inference
